"""empty message

Revision ID: ff703093d4df
Revises: 
Create Date: 2025-05-23 12:11:45.408432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff703093d4df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='marketplace'
    )
    op.create_table('shop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='marketplace'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='marketplace'
    )
    op.create_table('shop_products',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace.product.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['marketplace.shop.id'], ),
    sa.PrimaryKeyConstraint('shop_id', 'product_id'),
    schema='marketplace'
    )
    op.create_table('user_basket',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace.product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['marketplace.user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'product_id'),
    schema='marketplace'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_basket', schema='marketplace')
    op.drop_table('shop_products', schema='marketplace')
    op.drop_table('user', schema='marketplace')
    op.drop_table('shop', schema='marketplace')
    op.drop_table('product', schema='marketplace')
    # ### end Alembic commands ###
